name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven Testing
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # Setup java 11 to be default (sonar-scanner requirement as of 5.x)
      - name: Set Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      # Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Run sonar-scanner
      - name: SonarQube Scan
        run: sonar-scanner
             -D sonar.host.url=${{ secrets.SONAR_URL }}
             -D sonar.login=${{ secrets.SONAR_TOKEN }}
             -D sonar.organization=${{ secrets.SONAR_ORGANIZATION }}
             -D sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
             -D sonar.sources=src/
             -D sonar.junit.reportsPath=target/surefire-reports/ 
             -D sonar.jacoco.reportsPath=target/jacoco.exec 
             -D sonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
             -D sonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
